version: '2'

services:
    zookeeper:
        image: ubuntu/zookeeper:edge
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - 22181:2181
        network_mode: "host"

    kafka:
        image: ubuntu/kafka
        depends_on:
            - zookeeper
        ports:
            - 29092:29092
        network_mode: "host"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    jupyter_env:
        # image: work-env             # can be local image
        build:
            context: .
            dockerfile: Dockerfile_gpu_env
        depends_on:
            - kafka
        ports:
            - 8888:8888
        command: ["jupyter", "lab", "--no-browser", "--ip=0.0.0.0", "--port=8888", "--allow-root"]
        volumes:
            - ./work_dir:/work
        deploy:
            resources:
                reservations:
                  devices:
                      - driver: nvidia
                        count: 1
                      #   device_ids: ['0', '3']
                        capabilities: [gpu]

